Restart instruments only if it did not launch the target.
As evinced not only by it returning an error, but by not having written a log.
instruments has only been observed to return an error if it fails to launch the target,
but we should only ever restart it if it didn't run at all, to avoid overwriting results.

diff --git a/Supporting Files/CI/subliminal-test b/Supporting Files/CI/subliminal-test
--- a/Supporting Files/CI/subliminal-test
+++ b/Supporting Files/CI/subliminal-test
@@ -501,7 +501,8 @@ launch_instruments () {
 }
 
 launch_instruments
-if [ $? -ne 0 ]; then
+RESULT_LOG="$RESULTS_DIR/Run 1/Automation Results.plist"
+if [ $? -ne 0 ] && [ ! -e "$RESULT_LOG" ]; then
 	# Under poorly understood circumstances, in certain CI environments like Travis, 
 	# instruments may fail to launch what otherwise appears to be a perfectly good app 
 	# (in that an app prepared exactly the same way may be run without error on another run), 
@@ -521,8 +522,7 @@ fi
 ### Process results
 echo "\n\nProcessing results..."
 
-# Parse test success or failure out of the run .plist
-RESULT_LOG="$RESULTS_DIR/Run 1/Automation Results.plist"
+# Parse test success or failure out of the result log
 TEST_STATUS=0
 grep -q "This was a focused run." "$RESULT_LOG"
 if [ $? -eq 0 ]; then
