Merge the various simulator scripts into `simulator-set`.
To eliminate redundant logic and simulator restarts, and simplify the CI setup.

diff --git a/Supporting Files/CI/subliminal-test b/Supporting Files/CI/subliminal-test
--- a/Supporting Files/CI/subliminal-test
+++ b/Supporting Files/CI/subliminal-test
@@ -292,7 +292,7 @@ reset_simulator_or_device () {
 	local reset_success=0
 	
 	if [[ -n "$SIM_DEVICE" ]]; then
-		"$SCRIPT_DIR/reset_simulator"
+		"$SCRIPT_DIR/simulator-set" --reset
 		reset_success=$?
 		if [ $reset_success -eq 0 ]; then
 			echo "Successfully reset iOS Simulator."
@@ -505,28 +505,14 @@ build_app
 echo "\n\nPreparing to install app..."
 
 if [[ -n "$SIM_DEVICE" ]]; then
-	# Set the simulator's device type
-	echo "\nSetting simulator device type..."
-	"$SCRIPT_DIR/set_simulator_device" "$SIM_DEVICE"
-	if [ $? -eq 0 ]; then
-		echo "Successfully set simulator device type."
+	# Configure the simulator's properties
+	echo "\nConfiguring the simulator for testing..."
+
+	if [[ -n "$SIM_VERSION" ]]; then
+		echo "- Setting the version to $SIM_VERSION"
 	else
-		echo "\nERROR: Could not set the simulator's device type."
-		cleanup_and_exit 1
-	fi
-
-	# Set the simulator's version
-	echo "\nSetting simulator version..."
-
-	if [[ -z "$SIM_VERSION" ]]; then
-		echo "\nSimulator version not specified. Defaulting to latest simulator installed."
 		SIM_VERSION=`xcrun xcodebuild -showsdks | grep "iphonesimulator" | sort -r | head -n 1 | sed -E 's|^.*iphonesimulator(.*)$|\1|'`
-	fi
-
-	"$SCRIPT_DIR/set_simulator_version" "$SIM_VERSION"
-	if [ $? -ne 0 ]; then
-		echo "\nERROR: Could not set the simulator's version."
-		cleanup_and_exit 1
+		echo "- Setting the version to $SIM_VERSION (Simulator version not specified--defaulting to latest simulator installed)"
 	fi
 
 	# The instruments command-line tool picks an arbitrary SDK depending on toolchain version:
@@ -535,20 +521,26 @@ if [[ -n "$SIM_DEVICE" ]]; then
 	# to force it to use the simulator's current setting
 	enable_SDK_version_or_all "$SIM_VERSION"
 
-	echo "\nSuccessfully set simulator version."
+	echo "- Setting the device to \"$SIM_DEVICE\""
+	echo "- Resetting simulator content and settings"
 
-	# Reset the simulator
-	# This has got to be done after setting the simulator's version
-	# so that we wipe the appropriate content and settings
-	echo "\nResetting simulator content and settings..."
-	reset_simulator_or_device
+	"$SCRIPT_DIR/simulator-set" --device "$SIM_DEVICE" --version "$SIM_VERSION" --reset
+	if [ $? -ne 0 ]; then
+		echo "\nERROR: Could not configure the simulator."
+		cleanup_and_exit 1
+	fi
+	echo "Successfully configured the Simulator for testing."
 
 	# instruments will actually install the app in the simulator
 else
 	echo "\n\nInstalling app..."
 	reinstall_app_on_device
+	if [ $? -ne 0 ]; then
+		echo "\nERROR: Could not install the app on the device."
+		cleanup_and_exit 1
+	fi
+	echo "Successfully installed app."
 fi
-[ $? -eq 0 ] || cleanup_and_exit 1
 
 # Set paths to save instruments' output (at least temporarily)
 RUN_DIR=`mktemp -d /tmp/subliminal-test.run.XXXXXX`
